import { db } from "@/lib/db"
import { users, profiles } from "@/lib/db/schema"
import { hashPassword } from "@/lib/auth/password"

const OFFICIAL_GROOMS = [
  {
    phone: "7970094797",
    username: "Sandeep Mewada",
    type: "GROOM",
    gotraSelf: "Dod",
    gotraMother: "Baghela",
    dob: "2000-01-01",
    height: "5'8\"",
    education: "Graduate",
    profession: "-",
    district: "Bhopal",
    community: "Mewada",
    fatherName: "Ramdayal Mewada",
    motherName: "Antar Bai",
    address: "-",
    brothers: "0",
    sisters: "4",
    familyType: "-",
    parentsOccupation: "Farmer",
    image: "sandeep.jpeg",
  },
  {
    phone: "6260134370",
    username: "Sarvesh Rajput",
    type: "GROOM",
    gotraSelf: "Dod",
    gotraMother: "Rathore",
    dob: "2001-01-01",
    height: "5'7\"",
    education: "Second Year",
    profession: "Bajaj Collection Agent",
    district: "Bhopal",
    community: "Rajput",
    fatherName: "Late Kailash Singh",
    motherName: "Ramshree Bai",
    address: "Phanda Kalan, Bhopal",
    brothers: "3",
    sisters: "1",
    familyType: "Joint Family",
    parentsOccupation: "Mother: Housewife",
    image: "sarvesh.jpeg",
  },
  {
    phone: "7828767625",
    username: "Hirdesh Mewada",
    type: "GROOM",
    gotraSelf: "Hada",
    gotraMother: "Dod",
    dob: "2002-01-01",
    height: "5'9\"",
    education: "12th Pass",
    profession: "Student",
    district: "Sehore",
    community: "Mewada",
    fatherName: "Laxmi Narayan Mewada",
    motherName: "Anusuiya Mewada",
    address: "Dhamaniya",
    brothers: "0",
    sisters: "1",
    familyType: "Joint Family",
    parentsOccupation: "Father: Farmer, Mother: Housewife",
    image: "hirdesh.jpeg",
  },
  {
    phone: "7089729322",
    username: "Vikash Mewada",
    type: "GROOM",
    gotraSelf: "Baghela",
    gotraMother: "Shankla",
    dob: "1998-01-01",
    height: "5'10\"",
    education: "Graduate",
    profession: "Podcast Producer",
    district: "Bhopal",
    community: "Mewada",
    fatherName: "Ghisilal Mewada",
    motherName: "Rukmani Bai",
    address: "-",
    brothers: "2",
    sisters: "0",
    familyType: "-",
    parentsOccupation: "Farmer",
    image: "vikash.jpeg",
  },
  {
    phone: "6267534211",
    username: "Arpit Rajput",
    type: "GROOM",
    gotraSelf: "Dod",
    gotraMother: "Rathore",
    dob: "2003-01-01",
    height: "5'8\"",
    education: "12th Pass",
    profession: "Student",
    district: "Bhopal",
    community: "Rajput",
    fatherName: "Radheshyam Rajput",
    motherName: "Parvati Rajput",
    address: "Phanda Kalan",
    brothers: "1",
    sisters: "0",
    familyType: "Joint Family",
    parentsOccupation: "Father: Farmer, Mother: Housewife",
    image: "arpit.jpeg",
  },
  {
    phone: "6266550727",
    username: "Rajkumar Mewada",
    type: "GROOM",
    gotraSelf: "Pipada",
    gotraMother: "Kilodiya",
    dob: "2002-07-12",
    height: "5'7\"",
    education: "12th Pass",
    profession: "-",
    district: "Sehore",
    community: "Mewada",
    fatherName: "Mohan Singh",
    motherName: "Pushpa Bai",
    address: "Chhatri, Sehore",
    brothers: "1",
    sisters: "3",
    familyType: "6 Members",
    parentsOccupation: "-",
    image: "rajkumar.jpeg",
  },
  {
    phone: "0000000007",
    username: "Ankit Mewada",
    type: "GROOM",
    gotraSelf: "Dava",
    gotraMother: "Baghela",
    dob: "2001-01-01",
    height: "5'9\"",
    education: "-",
    profession: "-",
    district: "Sehore",
    community: "Mewada",
    fatherName: "Ramcharan Mewada",
    motherName: "Singar Bai",
    address: "-",
    brothers: "1",
    sisters: "1",
    familyType: "-",
    parentsOccupation: "Farmer",
    image: "ankit.jpeg",
  },
  {
    phone: "6263611436",
    username: "Animesh Mewada",
    type: "GROOM",
    gotraSelf: "Sisodiya",
    gotraMother: "Bordiya",
    dob: "2005-04-27",
    height: "5'11\"",
    education: "B.Com (Computer), DCA, MBA (Pursuing)",
    profession: "Private Job",
    district: "Bhopal",
    community: "Mewada",
    fatherName: "Sher Singh Mewada",
    motherName: "Rekha Mewada",
    address: "Ratanpur, Bhopal",
    brothers: "0",
    sisters: "1",
    familyType: "Nuclear Family",
    parentsOccupation: "Father: Land & Dairy Business, Mother: Housewife",
    image: "animesh.jpeg",
  },
  {
    phone: "7400640496",
    username: "Rohit Mewada",
    type: "GROOM",
    gotraSelf: "Pathariya",
    gotraMother: "Sisodiya",
    dob: "2003-12-15",
    height: "5'10\"",
    education: "Competitive Exam Aspirant",
    profession: "Student",
    district: "Bhopal",
    community: "Mewada",
    fatherName: "Kaluram Mewada",
    motherName: "Rekha Mewada",
    address: "Phanda Kalan, Bhopal",
    brothers: "1 (Ajey)",
    sisters: "-",
    familyType: "Joint Family",
    parentsOccupation: "Father: Farmer",
    image: "rohit.jpeg",
  },
  {
    phone: "7415120791",
    username: "Deepak Mewada",
    type: "GROOM",
    gotraSelf: "Budhana",
    gotraMother: "Khadwad",
    dob: "1997-01-01",
    height: "5'8\"",
    education: "Graduate",
    profession: "Private Job",
    district: "Bhopal",
    community: "Mewada",
    fatherName: "Kumar Singh Mewada",
    motherName: "Bhagwati Bai",
    address: "Phanda Kalan",
    brothers: "3 (Total 4)",
    sisters: "1",
    familyType: "Joint Family",
    parentsOccupation: "Farmer",
    image: "deepak.jpeg",
  },
  {
    phone: "9669753117",
    username: "Hritik Mewada",
    type: "GROOM",
    gotraSelf: "Bhati",
    gotraMother: "Daba",
    dob: "2005-07-09",
    height: "5'9\"",
    education: "12th Pass",
    profession: "Student",
    district: "Bhopal",
    community: "Mewada",
    fatherName: "Bhagwan Singh",
    motherName: "Bhuriya Bai",
    address: "Phanda",
    brothers: "1 (Kuldeep)",
    sisters: "1 (Aarti)",
    familyType: "Nuclear Family",
    parentsOccupation: "Father: Farmer",
    image: "hritik.jpeg",
  },
]

async function seed() {
  console.log("🌱 Seeding database...")

  const password = await hashPassword("password123")

  for (const groom of OFFICIAL_GROOMS) {
    const [user] = await db
      .insert(users)
      .values({
        phone: groom.phone,
        username: groom.username,
        passwordHash: password,
        role: "USER",
        isApproved: true,
      })
      .onConflictDoUpdate({
        target: users.phone,
        set: { username: groom.username, isApproved: true },
      })
      .returning()

    await db
      .insert(profiles)
      .values({
        userId: user.id,
        type: groom.type as any,
        visible: true,
        approvalStatus: "APPROVED",
        imagePath: groom.image,
        dob: groom.dob,
        height: groom.height,
        gotraSelf: groom.gotraSelf,
        gotraMother: groom.gotraMother,
        education: groom.education,
        profession: groom.profession,
        district: groom.district,
        community: groom.community,
        fatherName: groom.fatherName,
        motherName: groom.motherName,
        address: groom.address,
        contact: groom.phone,
        brothers: groom.brothers,
        sisters: groom.sisters,
        familyType: groom.familyType,
        parentsOccupation: groom.parentsOccupation,
      })
      .onConflictDoUpdate({
        target: profiles.userId,
        set: {
          type: groom.type as any,
          visible: true,
          approvalStatus: "APPROVED",
          imagePath: groom.image,
          dob: groom.dob,
          height: groom.height,
          gotraSelf: groom.gotraSelf,
          gotraMother: groom.gotraMother,
          education: groom.education,
          profession: groom.profession,
          district: groom.district,
          community: groom.community,
          fatherName: groom.fatherName,
          motherName: groom.motherName,
          address: groom.address,
          contact: groom.phone,
          brothers: groom.brothers,
          sisters: groom.sisters,
          familyType: groom.familyType,
          parentsOccupation: groom.parentsOccupation,
        },
      })
  }

  // Seed super admin
  const [superAdmin] = await db
    .insert(users)
    .values({
      phone: "6267282908",
      username: "Pramod Rajput",
      passwordHash: password,
      role: "SUPER_ADMIN",
      isApproved: true,
    })
    .onConflictDoUpdate({
      target: users.phone,
      set: { role: "SUPER_ADMIN", isApproved: true },
    })
    .returning()

  await db
    .insert(profiles)
    .values({
      userId: superAdmin.id,
      type: "GROOM",
      visible: true,
      approvalStatus: "APPROVED",
      bio: "System Super Administrator",
      dob: "1990-01-01",
      height: "5'10\"",
      gotraSelf: "System",
      gotraMother: "System",
      education: "IT",
      profession: "Administrator",
      district: "Bhopal",
      community: "Mewada",
      contact: superAdmin.phone,
    })
    .onConflictDoUpdate({
      target: profiles.userId,
      set: {
        type: "GROOM",
        visible: true,
        approvalStatus: "APPROVED",
        bio: "System Super Administrator",
        district: "Bhopal",
        community: "Mewada",
      },
    })

  console.log("✅ Seeding complete.")
}

seed().catch((err) => {
  console.error(err)
  process.exit(1)
})
